name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image with a new name
        run: |
          # Change the image name and tag as needed
          IMAGE_NAME="ghcr.io/Soumyaworks/manylinux2014-llvm:12-x86_64"
          docker build . --tag $IMAGE_NAME
          docker run $IMAGE_NAME
          docker push $IMAGE_NAME
