name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image with a new name
        run: |
          docker build . --tag ghcr.io/soumyaworks/manylinux2014-llvm:12-x86_64
          docker run ghcr.io/soumyaworks/manylinux2014-llvm:12-x86_64
          docker push ghcr.io/soumyaworks/manylinux2014-llvm:12-x86_64
